name: GoLinter
on: [push]
jobs: 
  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: golangci/golangci-lint-actions@v3
        with:
          version: v1.29